/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTiktokRouteImport } from './routes/dashboard/tiktok'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardTiktokIndexRouteImport } from './routes/dashboard/tiktok/index'
import { Route as DashboardTiktokRepostRouteImport } from './routes/dashboard/tiktok/repost'
import { Route as DashboardTiktokLikeRouteImport } from './routes/dashboard/tiktok/like'
import { Route as DashboardTiktokFavoriteRouteImport } from './routes/dashboard/tiktok/favorite'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTiktokRoute = DashboardTiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTiktokIndexRoute = DashboardTiktokIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTiktokRoute,
} as any)
const DashboardTiktokRepostRoute = DashboardTiktokRepostRouteImport.update({
  id: '/repost',
  path: '/repost',
  getParentRoute: () => DashboardTiktokRoute,
} as any)
const DashboardTiktokLikeRoute = DashboardTiktokLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => DashboardTiktokRoute,
} as any)
const DashboardTiktokFavoriteRoute = DashboardTiktokFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => DashboardTiktokRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/tiktok': typeof DashboardTiktokRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tiktok/favorite': typeof DashboardTiktokFavoriteRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/tiktok/': typeof DashboardTiktokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tiktok/favorite': typeof DashboardTiktokFavoriteRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/tiktok': typeof DashboardTiktokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/tiktok': typeof DashboardTiktokRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tiktok/favorite': typeof DashboardTiktokFavoriteRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/tiktok/': typeof DashboardTiktokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/tiktok'
    | '/dashboard/'
    | '/dashboard/tiktok/favorite'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/tiktok/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/tiktok/favorite'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/tiktok'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/tiktok'
    | '/dashboard/'
    | '/dashboard/tiktok/favorite'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/tiktok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tiktok': {
      id: '/dashboard/tiktok'
      path: '/tiktok'
      fullPath: '/dashboard/tiktok'
      preLoaderRoute: typeof DashboardTiktokRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tiktok/': {
      id: '/dashboard/tiktok/'
      path: '/'
      fullPath: '/dashboard/tiktok/'
      preLoaderRoute: typeof DashboardTiktokIndexRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
    '/dashboard/tiktok/repost': {
      id: '/dashboard/tiktok/repost'
      path: '/repost'
      fullPath: '/dashboard/tiktok/repost'
      preLoaderRoute: typeof DashboardTiktokRepostRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
    '/dashboard/tiktok/like': {
      id: '/dashboard/tiktok/like'
      path: '/like'
      fullPath: '/dashboard/tiktok/like'
      preLoaderRoute: typeof DashboardTiktokLikeRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
    '/dashboard/tiktok/favorite': {
      id: '/dashboard/tiktok/favorite'
      path: '/favorite'
      fullPath: '/dashboard/tiktok/favorite'
      preLoaderRoute: typeof DashboardTiktokFavoriteRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
  }
}

interface DashboardTiktokRouteChildren {
  DashboardTiktokFavoriteRoute: typeof DashboardTiktokFavoriteRoute
  DashboardTiktokLikeRoute: typeof DashboardTiktokLikeRoute
  DashboardTiktokRepostRoute: typeof DashboardTiktokRepostRoute
  DashboardTiktokIndexRoute: typeof DashboardTiktokIndexRoute
}

const DashboardTiktokRouteChildren: DashboardTiktokRouteChildren = {
  DashboardTiktokFavoriteRoute: DashboardTiktokFavoriteRoute,
  DashboardTiktokLikeRoute: DashboardTiktokLikeRoute,
  DashboardTiktokRepostRoute: DashboardTiktokRepostRoute,
  DashboardTiktokIndexRoute: DashboardTiktokIndexRoute,
}

const DashboardTiktokRouteWithChildren = DashboardTiktokRoute._addFileChildren(
  DashboardTiktokRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardTiktokRoute: typeof DashboardTiktokRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardTiktokRoute: DashboardTiktokRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
