/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccountsRouteImport } from './routes/dashboard/accounts'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardInstagramRouteImport } from './routes/dashboard/instagram'
import { Route as DashboardTiktokRouteImport } from './routes/dashboard/tiktok'
import { Route as DashboardInstagramIndexRouteImport } from './routes/dashboard/instagram/index'
import { Route as DashboardInstagramRepostRouteImport } from './routes/dashboard/instagram/repost'
import { Route as DashboardTiktokIndexRouteImport } from './routes/dashboard/tiktok/index'
import { Route as DashboardTiktokLikeRouteImport } from './routes/dashboard/tiktok/like'
import { Route as DashboardTiktokRepostRouteImport } from './routes/dashboard/tiktok/repost'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountsRoute = DashboardAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInstagramRoute = DashboardInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTiktokRoute = DashboardTiktokRouteImport.update({
  id: '/tiktok',
  path: '/tiktok',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInstagramIndexRoute = DashboardInstagramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardInstagramRoute,
} as any)
const DashboardInstagramRepostRoute =
  DashboardInstagramRepostRouteImport.update({
    id: '/repost',
    path: '/repost',
    getParentRoute: () => DashboardInstagramRoute,
  } as any)
const DashboardTiktokIndexRoute = DashboardTiktokIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTiktokRoute,
} as any)
const DashboardTiktokLikeRoute = DashboardTiktokLikeRouteImport.update({
  id: '/like',
  path: '/like',
  getParentRoute: () => DashboardTiktokRoute,
} as any)
const DashboardTiktokRepostRoute = DashboardTiktokRepostRouteImport.update({
  id: '/repost',
  path: '/repost',
  getParentRoute: () => DashboardTiktokRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/instagram': typeof DashboardInstagramRouteWithChildren
  '/dashboard/tiktok': typeof DashboardTiktokRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/instagram/repost': typeof DashboardInstagramRepostRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/instagram/': typeof DashboardInstagramIndexRoute
  '/dashboard/tiktok/': typeof DashboardTiktokIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/instagram/repost': typeof DashboardInstagramRepostRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/instagram': typeof DashboardInstagramIndexRoute
  '/dashboard/tiktok': typeof DashboardTiktokIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/accounts': typeof DashboardAccountsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/instagram': typeof DashboardInstagramRouteWithChildren
  '/dashboard/tiktok': typeof DashboardTiktokRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/instagram/repost': typeof DashboardInstagramRepostRoute
  '/dashboard/tiktok/like': typeof DashboardTiktokLikeRoute
  '/dashboard/tiktok/repost': typeof DashboardTiktokRepostRoute
  '/dashboard/instagram/': typeof DashboardInstagramIndexRoute
  '/dashboard/tiktok/': typeof DashboardTiktokIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/instagram'
    | '/dashboard/tiktok'
    | '/dashboard/'
    | '/dashboard/instagram/repost'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/instagram/'
    | '/dashboard/tiktok/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard'
    | '/dashboard/instagram/repost'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/instagram'
    | '/dashboard/tiktok'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/accounts'
    | '/dashboard/analytics'
    | '/dashboard/instagram'
    | '/dashboard/tiktok'
    | '/dashboard/'
    | '/dashboard/instagram/repost'
    | '/dashboard/tiktok/like'
    | '/dashboard/tiktok/repost'
    | '/dashboard/instagram/'
    | '/dashboard/tiktok/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/accounts': {
      id: '/dashboard/accounts'
      path: '/accounts'
      fullPath: '/dashboard/accounts'
      preLoaderRoute: typeof DashboardAccountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/instagram': {
      id: '/dashboard/instagram'
      path: '/instagram'
      fullPath: '/dashboard/instagram'
      preLoaderRoute: typeof DashboardInstagramRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tiktok': {
      id: '/dashboard/tiktok'
      path: '/tiktok'
      fullPath: '/dashboard/tiktok'
      preLoaderRoute: typeof DashboardTiktokRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/instagram/': {
      id: '/dashboard/instagram/'
      path: '/'
      fullPath: '/dashboard/instagram/'
      preLoaderRoute: typeof DashboardInstagramIndexRouteImport
      parentRoute: typeof DashboardInstagramRoute
    }
    '/dashboard/instagram/repost': {
      id: '/dashboard/instagram/repost'
      path: '/repost'
      fullPath: '/dashboard/instagram/repost'
      preLoaderRoute: typeof DashboardInstagramRepostRouteImport
      parentRoute: typeof DashboardInstagramRoute
    }
    '/dashboard/tiktok/': {
      id: '/dashboard/tiktok/'
      path: '/'
      fullPath: '/dashboard/tiktok/'
      preLoaderRoute: typeof DashboardTiktokIndexRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
    '/dashboard/tiktok/like': {
      id: '/dashboard/tiktok/like'
      path: '/like'
      fullPath: '/dashboard/tiktok/like'
      preLoaderRoute: typeof DashboardTiktokLikeRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
    '/dashboard/tiktok/repost': {
      id: '/dashboard/tiktok/repost'
      path: '/repost'
      fullPath: '/dashboard/tiktok/repost'
      preLoaderRoute: typeof DashboardTiktokRepostRouteImport
      parentRoute: typeof DashboardTiktokRoute
    }
  }
}

interface DashboardInstagramRouteChildren {
  DashboardInstagramRepostRoute: typeof DashboardInstagramRepostRoute
  DashboardInstagramIndexRoute: typeof DashboardInstagramIndexRoute
}

const DashboardInstagramRouteChildren: DashboardInstagramRouteChildren = {
  DashboardInstagramRepostRoute: DashboardInstagramRepostRoute,
  DashboardInstagramIndexRoute: DashboardInstagramIndexRoute,
}

const DashboardInstagramRouteWithChildren =
  DashboardInstagramRoute._addFileChildren(DashboardInstagramRouteChildren)

interface DashboardTiktokRouteChildren {
  DashboardTiktokLikeRoute: typeof DashboardTiktokLikeRoute
  DashboardTiktokRepostRoute: typeof DashboardTiktokRepostRoute
  DashboardTiktokIndexRoute: typeof DashboardTiktokIndexRoute
}

const DashboardTiktokRouteChildren: DashboardTiktokRouteChildren = {
  DashboardTiktokLikeRoute: DashboardTiktokLikeRoute,
  DashboardTiktokRepostRoute: DashboardTiktokRepostRoute,
  DashboardTiktokIndexRoute: DashboardTiktokIndexRoute,
}

const DashboardTiktokRouteWithChildren = DashboardTiktokRoute._addFileChildren(
  DashboardTiktokRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAccountsRoute: typeof DashboardAccountsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardInstagramRoute: typeof DashboardInstagramRouteWithChildren
  DashboardTiktokRoute: typeof DashboardTiktokRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountsRoute: DashboardAccountsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardInstagramRoute: DashboardInstagramRouteWithChildren,
  DashboardTiktokRoute: DashboardTiktokRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
